package com.simformsolutions.exception.trycatch;



public class Main {
	public static void main(String[] args) {

		// outer try block
		try {
			// inner try block 1
			try {
				int b = 39 / 0;
			}
			// catch block of inner try block 1
			catch (ArithmeticException e) {
				System.out.println(e);
			}

			// inner try block 2
			try {
				int a[] = new int[5];

				// assigning the value out of array bounds
				a[5] = 4;
			}

			// catch block of inner try block 2
			catch (ArithmeticException e) {
				System.out.println(e);
			}

			System.out.println("other statement");
		}
		// catch block of outer try block
		catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("handled the exception (outer catch)"+e);
		}

		System.out.println("normal flow..");
	}
}
